#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect the requirements

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /usr/share/nginx/html/index.html
service nginx start
