#!/usr/bin/env bash
# Bash script that install and configure HAproxy on your lb-01 server.

configurations="\
defaults
	mode http
	timeout connect 5000
	timeout client 5000
	timeout server 5000
frontend load_balancer
	bind 18.234.80.181:80
	default_backend servers
backend servers
	server 531078-web-01 100.25.12.124
	server 531078-web-02 54.236.45.187
"
sudo su
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 11303-web-01 3.238.126.83:80 check\n\tserver 11303-web-02 18.232.125.225:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
