#!/usr/bin/env bash
# Bash script that configures and fix a server
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sudo ./2-print.py
