#!/usr/bin/env bash
# Bash script that configures a server
sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
service nginx restart
nginx -s reload
kill -9 "$(cat /var/run/nginx.pid)"
