#!/usr/bin/env bash
# Bash script that configures and fix a server
ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
