#!/usr/bin/env bash

IFS=":"

# Open the /etc/passwd file for reading
while read -r username _ uid _ _ home _
do
    # Display the required information
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
