#!/usr/bin/env bash
# Open the /etc/passwd file for reading in a formating form

IFS=":"
while read -r Username Password UserID GID GECOS Home Command
do
	echo "The user $Username is part of the $GID gang, lives in $Home and rides $Command. $UserID's place is protected by the passcode $Password, more info about the user here: $GECOS"
done < /etc/passwd
