#!/usr/bin/env bash
# This script simplifies connecting to a server.

# Server details
server_name="ubuntu"
private_key="$HOME/.ssh/school"
localhost="54.237.107.23"

# Connect to the server
eval 'ssh -i "$private_key" "$server_name@$localhost"'

